### ISSUE TITLE
该项目的前端代码不是TS 编写的吧~~

### ISSUE THREAD

**Issue by ghost** [hubcarl/egg-react-typescript-boilerplate#1]
该项目的前端代码不是TS 编写的吧~~

**Comment by xiajinchun** [comment]
请问前端支持 .tsx 的写法吗？

**Comment by gundamlbn** [comment]
@xiajinchun 
我试了下是支持的
改下根目录的ts.config就行，
调整下 include和 exclude
使app/web下面的tsx文件进入编译对象
