### ISSUE TITLE
cannot find window.navigator.getUserMedia methods

### ISSUE THREAD

**Issue by 18566246732** [hubcarl/egg-react-typescript-boilerplate#5]
window对象被重写了吗？现在无法调起录音了

**Comment by hubcarl** [comment]
@18566246732  没有重写，具体见：

- https://developer.mozilla.org/zh-CN/docs/Web/API/Navigator/getUserMedia
- https://stackoverflow.com/questions/12407321/navigator-getusermedia

使用 navigator.mediaDevices.getUserMedia

https://developer.mozilla.org/zh-CN/docs/Web/API/MediaDevices/getUserMedia

**Comment by 18566246732** [comment]
可能是没用https的问题
